"use client";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "/api/backend";
const DEFAULTS = { dgcaMonth: "2026-07", topN: 50, direction: "bidirectional", dailyRoutePairs: 20, compareFlightsTime: "06:00", ixigoTime: "06:30", ixigoDriver: "chromium", ixigoDelay: 3, ixigoRetry: 2, dgcaTime: "09:30", scraperEnabled: true };

function JobStatus({ job, setJob }) {
  useEffect(() => { if (!job?.job_id || ["COMPLETED", "ERROR"].includes(job.status)) return; const timer = setInterval(() => fetch(`${API}/api/scrape/status/${job.job_id}`).then(r => r.json()).then(setJob).catch(() => {}), 1000); return () => clearInterval(timer); }, [job?.job_id, job?.status, setJob]);
  if (!job) return null;
  return <div className="scrape-status"><strong>{job.status}</strong><span>{job.completed_routes || 0} / {job.total_routes || "..."} directed routes completed</span><span>{job.available_count != null ? `${job.available_count} observations available / ${job.record_count || 0} records` : "Preparing route queue..."}</span>{job.routes?.length ? <div className="scrape-route-list">{job.routes.map(route => <div key={route.route}><span>{route.route}</span><span className={`scrape-${String(route.status).toLowerCase()}`}>{route.status}</span><small>{route.reason || route.completed_at || route.started_at || "queued"}</small></div>)}</div> : null}</div>;
}

export default function Settings() {
  const [settings, setSettings] = useState(DEFAULTS); const [saved, setSaved] = useState(false); const [dgca, setDgca] = useState(null); const [method, setMethod] = useState(null); const [config, setConfig] = useState(null); const [compareJob, setCompareJob] = useState(null); const [ixigoJob, setIxigoJob] = useState(null);
  useEffect(() => { try { setSettings({ ...DEFAULTS, ...JSON.parse(localStorage.getItem("airfareSettings") || "{}") }); } catch {} Promise.all([fetch(`${API}/api/dgca/status`).then(r => r.json()), fetch(`${API}/api/dgca/basket?top_n=50&direction_mode=bidirectional`).then(r => r.json()), fetch(`${API}/api/data-quality`).then(r => r.json()), fetch(`${API}/api/source-health`).then(r => r.json()), fetch(`${API}/api/scraper-config`).then(r => r.json())]).then(([status, basket, quality, sources, server]) => { setDgca(status); setMethod({ basket, quality, sources }); setConfig(server); }).catch(() => {}); }, []);
  const update = (key, value) => { setSettings(current => ({ ...current, [key]: value })); setSaved(false); };
  async function save(event) { event.preventDefault(); localStorage.setItem("airfareSettings", JSON.stringify(settings)); const response = await fetch(`${API}/api/scraper-config`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ daily_route_pairs: settings.dailyRoutePairs, compareflights_time: settings.compareFlightsTime, ixigo_time: settings.ixigoTime, ixigo_driver: settings.ixigoDriver, ixigo_route_delay_seconds: settings.ixigoDelay, ixigo_retry_count: settings.ixigoRetry, direction_mode: settings.direction }) }); if (response.ok) setConfig(await response.json()); setSaved(true); }
  async function start(source) { const response = await fetch(`${API}/api/scrape/${source}`, { method: "POST" }); const body = await response.json(); const next = { ...body, status: response.ok ? body.status : "ERROR" }; source === "ixigo" ? setIxigoJob(next) : setCompareJob(next); }
  const runCount = config?.directed_route_count || (settings.direction === "bidirectional" ? settings.dailyRoutePairs * 2 : settings.dailyRoutePairs);
  return <main className="page"><section className="grid">
    <div className="panel full"><h2>Collection Settings</h2><p className="muted">These values are shared with the backend worker through the runtime scraper configuration.</p><form className="settings-form" onSubmit={save}><label>DGCA month<input type="month" value={settings.dgcaMonth} onChange={e => update("dgcaMonth", e.target.value)} /></label><label>DGCA Top route pairs<select value={settings.topN} onChange={e => update("topN", Number(e.target.value))}><option value="25">25</option><option value="50">50</option><option value="75">75</option><option value="100">100</option></select></label><label>Daily source route pairs<select value={settings.dailyRoutePairs} onChange={e => update("dailyRoutePairs", Number(e.target.value))}><option value="10">10 pairs / 20 directions</option><option value="20">20 pairs / 40 directions</option><option value="30">30 pairs / 60 directions</option><option value="50">50 pairs / 100 directions</option></select></label><label>Direction mode<select value={settings.direction} onChange={e => update("direction", e.target.value)}><option value="bidirectional">Bidirectional</option><option value="unidirectional">Unidirectional</option><option value="merged">Merged pairs</option></select></label><label>CompareFlights daily time<input type="time" value={settings.compareFlightsTime} onChange={e => update("compareFlightsTime", e.target.value)} /></label><label>Ixigo daily time<input type="time" value={settings.ixigoTime} onChange={e => update("ixigoTime", e.target.value)} /></label><label>Ixigo browser driver<select value={settings.ixigoDriver} onChange={e => update("ixigoDriver", e.target.value)}><option value="chromium">Chromium</option><option value="firefox">Firefox</option><option value="webkit">WebKit</option></select></label><label>DGCA monthly refresh time<input type="time" value={settings.dgcaTime} onChange={e => update("dgcaTime", e.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={settings.scraperEnabled} onChange={e => update("scraperEnabled", e.target.checked)} /> Enable daily collection</label><button type="submit">Save settings</button>{saved && <span className="saved">Saved</span>}</form><div className="config-summary"><strong>Daily fetch scope: {settings.dailyRoutePairs} DGCA pairs → {runCount} directed routes per source</strong><span>CompareFlights: {settings.compareFlightsTime} · Ixigo: {settings.ixigoTime} · headless driver: {settings.ixigoDriver}</span></div></div>
    <div className="panel full"><h2>Daily Source Controls</h2><div className="source-settings"><div className="source-setting active"><span className="status-badge ok">ACTIVE</span><h3>CompareFlights OTA</h3><p>Daily import at {settings.compareFlightsTime}. {runCount} directed route searches are queued per run.</p><p><a href="https://compareflights.co.in" target="_blank" rel="noreferrer">Open original source</a></p><button type="button" onClick={() => start("compareflights")} disabled={["RUNNING", "QUEUED"].includes(compareJob?.status)}>{["RUNNING", "QUEUED"].includes(compareJob?.status) ? "Collection running..." : "Run CompareFlights now"}</button><JobStatus job={compareJob} setJob={setCompareJob} /></div><div className="source-setting active"><span className="status-badge ok">ACTIVE</span><h3>Ixigo OTA</h3><p>Daily headless {settings.ixigoDriver} stream capture at {settings.ixigoTime}. {runCount} directed route searches are queued per run.</p><p><a href="https://www.ixigo.com" target="_blank" rel="noreferrer">Open Ixigo</a> · <a href="https://www.ixigo.com/growth/api/v1/holidayCalendar" target="_blank" rel="noreferrer">Holiday calendar</a></p><button type="button" onClick={() => start("ixigo")} disabled={["RUNNING", "QUEUED"].includes(ixigoJob?.status)}>{["RUNNING", "QUEUED"].includes(ixigoJob?.status) ? "Collection running..." : "Run Ixigo now"}</button><JobStatus job={ixigoJob} setJob={setIxigoJob} /></div></div></div>
    <div className="panel wide"><h2>DGCA Monthly Cycle</h2><div className={`status-badge ${dgca?.status === "UPLOADED" ? "ok" : "warning"}`}>{dgca?.status || "Checking"}</div><p>{dgca?.message || "Checking previous-month workbook status."}</p><p className="muted">Expected {dgca?.expected_previous_month || "..."}; latest available {dgca?.latest_available_file || "..."}.</p><a href="https://www.dgca.gov.in/" target="_blank" rel="noreferrer">Open DGCA source</a></div>
    <div className="panel wide"><h2>Data & Method</h2><div className="metric-grid"><div><span className="metric-label">Daily source routes</span><strong>{runCount}</strong></div><div><span className="metric-label">DGCA basket</span><strong>{method?.basket?.count ?? "..."}</strong></div><div><span className="metric-label">Valid observations</span><strong>{method?.quality?.by_quality_status?.valid?.toLocaleString() ?? "..."}</strong></div><div><span className="metric-label">Sources</span><strong>{method?.sources?.length ?? "..."}</strong></div></div><ul className="compact-list"><li>DGCA pairs expand to both directions in bidirectional mode.</li><li>CompareFlights and Ixigo run independently and remain headless.</li><li>Holiday calendar is retained as source context for seasonality analysis.</li><li>Missing fare components remain unavailable rather than estimated.</li></ul></div>
  </section></main>;
}
