"use client";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "/api/backend";
const DEFAULTS = { dgcaMonth: "2026-07", topN: 50, direction: "bidirectional", dailyRoutePairs: 20, compareFlightsTime: "06:00", ixigoTime: "06:30", ixigoDelay: 3, ixigoRetry: 2, scraperDrivers: 4, compareHeadless: false, ixigoHeadless: false, dgcaTime: "09:30", scraperEnabled: true };
const activeStatuses = ["RUNNING", "QUEUED", "STOPPING"];

async function readResponseBody(response) {
  const text = await response.text();
  if (!text.trim()) return {};
  try {
    return JSON.parse(text);
  } catch {
    return { detail: text };
  }
}

function JobStatus({ job, setJob }) {
  useEffect(() => { if (!job?.job_id || ["COMPLETED", "STOPPED", "ERROR", "REJECTED", "NO_SCRAPE_PERFORMED"].includes(job.status)) return; const timer = setInterval(() => fetch(`${API}/api/scrape/status/${job.job_id}`).then(r => r.json()).then(setJob).catch(() => {}), 1000); return () => clearInterval(timer); }, [job?.job_id, job?.status, setJob]);
  if (!job) return null;
  if (job.status === "NO_SCRAPE_PERFORMED") return <div className="scrape-status"><strong>No scrape performed today</strong><span>{job.message || "No source snapshot is available for today."}</span><span>Latest available source data: {job.latest_data_date || "Unavailable"}</span></div>;
  return <div className="scrape-status"><strong>{job.status}</strong><span>{job.completed_routes || 0} / {job.total_routes || "..."} routes · {job.completed_tasks || 0} / {job.total_tasks || job.total_routes || "..."} tasks</span><span>{job.driver_count ? `${job.driver_count} parallel drivers allocated` : "Preparing driver pool..."} · {job.available_count != null ? `${job.available_count} observations available` : "Preparing queue..."}</span>{job.routes?.length ? <div className="scrape-route-list">{job.routes.map(route => <div key={route.task || route.route}><span>{route.task || route.route}</span><span className={`scrape-${String(route.status).toLowerCase()}`}>{route.status}</span><small>{route.reason || route.completed_at || route.started_at || "queued"}</small></div>)}</div> : null}</div>;
}

export default function Settings() {
  const [settings, setSettings] = useState(DEFAULTS); const [saved, setSaved] = useState(false); const [saveError, setSaveError] = useState(""); const [dgca, setDgca] = useState(null); const [method, setMethod] = useState(null); const [config, setConfig] = useState(null); const [compareJob, setCompareJob] = useState(null); const [ixigoJob, setIxigoJob] = useState(null);
  const [catalog, setCatalog] = useState([]); const [adaptorSource, setAdaptorSource] = useState("compareflights"); const [adaptorDate, setAdaptorDate] = useState(""); const [adaptorValidation, setAdaptorValidation] = useState(null); const [adaptorJob, setAdaptorJob] = useState(null); const [adaptorBusy, setAdaptorBusy] = useState(false);
  useEffect(() => { try { setSettings({ ...DEFAULTS, ...JSON.parse(localStorage.getItem("airfareSettings") || "{}") }); } catch {} Promise.all([fetch(`${API}/api/dgca/status`).then(r => r.json()), fetch(`${API}/api/dgca/basket?top_n=50&direction_mode=bidirectional`).then(r => r.json()), fetch(`${API}/api/data-quality`).then(r => r.json()), fetch(`${API}/api/source-health`).then(r => r.json()), fetch(`${API}/api/scraper-config`).then(r => r.json()), fetch(`${API}/api/source-data/dates`).then(r => r.json())]).then(([status, basket, quality, sources, server, dates]) => { setDgca(status); setMethod({ basket, quality, sources }); setConfig(server); setCatalog(dates.sources || []); setSettings(current => ({ ...current, dgcaMonth: server.dgca_month ?? current.dgcaMonth, topN: server.dgca_top_n ?? current.topN, dgcaTime: server.dgca_time ?? current.dgcaTime, scraperEnabled: server.scraper_enabled ?? current.scraperEnabled, dailyRoutePairs: server.daily_route_pairs ?? current.dailyRoutePairs, direction: server.direction_mode ?? current.direction, compareFlightsTime: server.compareflights_time ?? current.compareFlightsTime, ixigoTime: server.ixigo_time ?? current.ixigoTime, ixigoDelay: server.ixigo_route_delay_seconds ?? current.ixigoDelay, ixigoRetry: server.ixigo_retry_count ?? current.ixigoRetry, scraperDrivers: server.scraper_driver_count ?? current.scraperDrivers, compareHeadless: server.compareflights_headless ?? current.compareHeadless, ixigoHeadless: server.ixigo_headless ?? current.ixigoHeadless })); Promise.all((sources || []).filter(item => item.job_id).map(item => fetch(`${API}/api/scrape/status/${item.job_id}`).then(response => response.ok ? response.json() : null).catch(() => null))).then(jobs => jobs.filter(Boolean).forEach(job => { if (job.source === "Ixigo OTA") setIxigoJob(job); if (job.source === "CompareFlights OTA") setCompareJob(job); })); }).catch(() => {}); }, []);
  const update = (key, value) => { setSettings(current => ({ ...current, [key]: value })); setSaved(false); setSaveError(""); };
  async function save(event) { event.preventDefault(); setSaved(false); setSaveError(""); try { const payload = { daily_route_pairs: settings.dailyRoutePairs, compareflights_time: settings.compareFlightsTime, ixigo_time: settings.ixigoTime, dgca_month: settings.dgcaMonth, dgca_top_n: settings.topN, dgca_time: settings.dgcaTime, scraper_enabled: settings.scraperEnabled, compareflights_headless: settings.compareHeadless, ixigo_headless: settings.ixigoHeadless, ixigo_route_delay_seconds: settings.ixigoDelay, ixigo_retry_count: settings.ixigoRetry, scraper_driver_count: settings.scraperDrivers, ixigo_lead_days: [1, 7, 15, 30, 45], direction_mode: settings.direction }; const response = await fetch(`${API}/api/scraper-config`, { method: "PUT", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify(payload) }); const body = await readResponseBody(response); if (!response.ok) throw new Error(body?.detail?.message || body?.detail || "Settings could not be saved."); const server = body && typeof body === "object" && !Array.isArray(body) && Object.keys(body).length ? body : { ...payload }; localStorage.setItem("airfareSettings", JSON.stringify(settings)); setConfig(server); setSettings(current => ({ ...current, dgcaMonth: server.dgca_month ?? current.dgcaMonth, topN: server.dgca_top_n ?? current.topN, dgcaTime: server.dgca_time ?? current.dgcaTime, scraperEnabled: server.scraper_enabled ?? current.scraperEnabled, dailyRoutePairs: server.daily_route_pairs ?? current.dailyRoutePairs, direction: server.direction_mode ?? current.direction, compareFlightsTime: server.compareflights_time ?? current.compareFlightsTime, ixigoTime: server.ixigo_time ?? current.ixigoTime, ixigoDelay: server.ixigo_route_delay_seconds ?? current.ixigoDelay, ixigoRetry: server.ixigo_retry_count ?? current.ixigoRetry, scraperDrivers: server.scraper_driver_count ?? current.scraperDrivers, compareHeadless: server.compareflights_headless ?? current.compareHeadless, ixigoHeadless: server.ixigo_headless ?? current.ixigoHeadless })); setSaved(true); } catch (error) { setSaveError(error.message || "Settings could not be saved."); } }
  async function start(source) { const response = await fetch(`${API}/api/scrape/${source}`, { method: "POST" }); const body = await response.json(); const next = { ...body, status: response.ok ? body.status : "ERROR" }; source === "ixigo" ? setIxigoJob(next) : setCompareJob(next); }
  async function stop(source) { const job = source === "ixigo" ? ixigoJob : compareJob; if (!job?.job_id) return; const response = await fetch(`${API}/api/scrape/stop/${job.job_id}`, { method: "POST" }); if (response.ok) { const body = await response.json(); source === "ixigo" ? setIxigoJob(body) : setCompareJob(body); } }
  async function validateAndRunAdaptor() { if (!adaptorSource || !adaptorDate) return; setAdaptorBusy(true); setAdaptorValidation(null); setAdaptorJob(null); try { const check = await fetch(`${API}/api/adaptor/validate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: adaptorSource, run_date: adaptorDate }) }); const validation = await check.json(); setAdaptorValidation(validation); if (!check.ok && validation.valid !== false) throw new Error(validation.detail?.message || validation.detail || "Validation could not be completed."); let allowMissing = false; if (!validation.valid) { const missing = validation.missing_routes?.length ? ` Missing routes: ${validation.missing_routes.slice(0, 12).join(", ")}${validation.missing_routes.length > 12 ? "..." : ""}.` : ""; const proceed = window.confirm(`Validation rejected ${adaptorSource} on ${adaptorDate}.${missing} Click OK to publish the available routes as PARTIAL data, or Cancel to stop.`); if (!proceed) return; allowMissing = true; } else { const confirmed = window.confirm(`Publish ${validation.row_count.toLocaleString()} normalized observations for ${adaptorSource} on ${adaptorDate}? This creates a clean date file for the dashboard.`); if (!confirmed) return; } const response = await fetch(`${API}/api/adaptor/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: adaptorSource, run_date: adaptorDate, confirmed: true, allow_missing: allowMissing }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail?.message || body.detail || "Adaptor could not start."); setAdaptorJob(body); } catch (e) { setAdaptorValidation({ valid: false, message: e.message }); } finally { setAdaptorBusy(false); } }
  useEffect(() => { if (!adaptorJob?.job_id || ["COMPLETED", "COMPLETED_PARTIAL", "ERROR", "REJECTED"].includes(adaptorJob.status)) return; const timer = setInterval(() => fetch(`${API}/api/adaptor/status/${adaptorJob.job_id}`).then(r => r.json()).then(setAdaptorJob).catch(() => {}), 1000); return () => clearInterval(timer); }, [adaptorJob?.job_id, adaptorJob?.status]);
  const availableAdaptorDates = catalog.find(item => item.source === adaptorSource)?.dates || []; const runCount = config?.directed_route_count || (settings.direction === "bidirectional" ? settings.dailyRoutePairs * 2 : settings.dailyRoutePairs);
  useEffect(() => { if (!availableAdaptorDates.some(item => item.run_date === adaptorDate)) setAdaptorDate(availableAdaptorDates[0]?.run_date || ""); }, [availableAdaptorDates, adaptorDate]);
  return <main className="page"><section className="grid">
    <div className="panel full"><h2>Collection Settings</h2><p className="muted">These values are shared with the background worker. Each source has its own schedule and browser visibility; the driver limit is common and split when both run.</p><form className="settings-form" onSubmit={save}><label>DGCA month<input type="month" value={settings.dgcaMonth} onChange={e => update("dgcaMonth", e.target.value)} /></label><label>DGCA top route pairs<select value={settings.topN} onChange={e => update("topN", Number(e.target.value))}><option value="25">25</option><option value="50">50</option><option value="75">75</option><option value="100">100</option></select></label><label>Daily source route pairs<select value={settings.dailyRoutePairs} onChange={e => update("dailyRoutePairs", Number(e.target.value))}><option value="10">10 pairs / 20 directions</option><option value="20">20 pairs / 40 directions</option><option value="30">30 pairs / 60 directions</option><option value="50">50 pairs / 100 directions</option></select></label><label>Direction mode<select value={settings.direction} onChange={e => update("direction", e.target.value)}><option value="bidirectional">Bidirectional</option><option value="unidirectional">Unidirectional</option><option value="merged">Merged pairs</option></select></label><label>CompareFlights daily time<input type="time" value={settings.compareFlightsTime} onChange={e => update("compareFlightsTime", e.target.value)} /></label><label>Ixigo daily time<input type="time" value={settings.ixigoTime} onChange={e => update("ixigoTime", e.target.value)} /></label><label>DGCA monthly refresh time<input type="time" value={settings.dgcaTime} onChange={e => update("dgcaTime", e.target.value)} /></label><label>Max allowed parallel drivers<input type="number" min="1" max="16" value={settings.scraperDrivers} onChange={e => update("scraperDrivers", Number(e.target.value))} /></label><label className="checkbox-label"><input type="checkbox" checked={settings.compareHeadless} onChange={e => update("compareHeadless", e.target.checked)} /> CompareFlights headless</label><label className="checkbox-label"><input type="checkbox" checked={settings.ixigoHeadless} onChange={e => update("ixigoHeadless", e.target.checked)} /> Ixigo headless</label><label className="checkbox-label"><input type="checkbox" checked={settings.scraperEnabled} onChange={e => update("scraperEnabled", e.target.checked)} /> Enable daily collection</label><button type="submit">Save settings</button>{saved && <span className="saved">Saved</span>}{saveError && <span className="error">{saveError}</span>}</form><div className="config-summary"><strong>Daily fetch scope: {settings.dailyRoutePairs} DGCA pairs → {runCount} directed routes per source</strong><span>CompareFlights: {settings.compareFlightsTime} · Ixigo: {settings.ixigoTime} · {settings.scraperDrivers} shared drivers</span></div></div>
    <div className="panel full"><h2>Clean Data Adaptor</h2><p className="muted">Validate a source run before publishing it as one compact DDMMYYYY.json file. Incomplete coverage is rejected first; you can explicitly choose whether to cancel or publish the available routes as partial data.</p><div className="button-row"><label>Source<select value={adaptorSource} onChange={e => { setAdaptorSource(e.target.value); setAdaptorValidation(null); }}><option value="compareflights">CompareFlights OTA</option><option value="ixigo">Ixigo OTA</option></select></label><label>Date<select value={adaptorDate} onChange={e => setAdaptorDate(e.target.value)}>{availableAdaptorDates.map(item => <option key={item.run_date} value={item.run_date}>{item.run_date} · {item.data_mode}</option>)}</select></label><button type="button" onClick={validateAndRunAdaptor} disabled={adaptorBusy || !adaptorDate || ["QUEUED", "RUNNING"].includes(adaptorJob?.status)}>{adaptorBusy ? "Validating..." : "Validate and publish"}</button></div>{adaptorValidation && <div className={`notice ${adaptorValidation.valid ? "success-notice" : ""}`}><strong>{adaptorValidation.valid ? "Ready to publish" : "Rejected"}</strong><span> {adaptorValidation.message}</span><br /><span>{adaptorValidation.found_route_count || 0} / {adaptorValidation.expected_route_count || 0} routes · {(adaptorValidation.row_count || 0).toLocaleString()} rows{adaptorValidation.missing_routes?.length ? ` · Missing: ${adaptorValidation.missing_routes.slice(0, 8).join(", ")}` : ""}</span></div>}{adaptorJob && <div className="scrape-status"><strong>{adaptorJob.status === "COMPLETED_PARTIAL" ? "PUBLISHED WITH MISSED ROUTES" : adaptorJob.status}</strong><span>{adaptorJob.processed_routes || 0} / {adaptorJob.total_routes || 0} routes · {adaptorJob.progress_pct || 0}% · {(adaptorJob.rows_written || 0).toLocaleString()} rows written</span>{adaptorJob.missing_routes?.length ? <span>Missed routes retained in validation: {adaptorJob.missing_routes.join(", ")}</span> : null}{adaptorJob.output_file && <span>{adaptorJob.output_file}</span>}{adaptorJob.error && <span className="error">{adaptorJob.error}</span>}</div>}</div>
    <div className="panel full"><h2>Daily Source Controls</h2><div className="source-settings"><div className="source-setting active"><span className="status-badge ok">ACTIVE</span><h3>CompareFlights OTA</h3><p>Live scrape at {settings.compareFlightsTime}. {runCount} directed route searches across T+1/T+7/T+15/T+30/T+45. Browser mode: {settings.compareHeadless ? "headless" : "visible"}.</p><p><a href="https://compareflights.co.in" target="_blank" rel="noreferrer">Open original source</a></p><button type="button" onClick={() => start("compareflights")} disabled={activeStatuses.includes(compareJob?.status)}>{activeStatuses.includes(compareJob?.status) ? "Collection running..." : "Run CompareFlights now"}</button><button type="button" onClick={() => stop("compareflights")} disabled={!compareJob?.job_id || ["COMPLETED", "STOPPED", "ERROR"].includes(compareJob?.status)}>Stop</button><JobStatus job={compareJob} setJob={setCompareJob} /></div><div className="source-setting active"><span className="status-badge ok">ACTIVE</span><h3>Ixigo OTA</h3><p>Live Chromium stream scrape at {settings.ixigoTime}, across T+1/T+7/T+15/T+30/T+45. Browser mode: {settings.ixigoHeadless ? "headless" : "visible"}.</p><p><a href="https://www.ixigo.com" target="_blank" rel="noreferrer">Open Ixigo</a> · <a href="https://www.ixigo.com/growth/api/v1/holidayCalendar" target="_blank" rel="noreferrer">Holiday calendar</a></p><button type="button" onClick={() => start("ixigo")} disabled={activeStatuses.includes(ixigoJob?.status)}>{activeStatuses.includes(ixigoJob?.status) ? "Collection running..." : "Run Ixigo now"}</button><button type="button" onClick={() => stop("ixigo")} disabled={!ixigoJob?.job_id || ["COMPLETED", "STOPPED", "ERROR"].includes(ixigoJob?.status)}>Stop</button><JobStatus job={ixigoJob} setJob={setIxigoJob} /></div></div></div>
    <div className="panel wide"><h2>DGCA Monthly Cycle</h2><div className={`status-badge ${dgca?.status === "UPLOADED" ? "ok" : "warning"}`}>{dgca?.status || "Checking"}</div><p>{dgca?.message || "Checking previous-month workbook status."}</p><p className="muted">Expected {dgca?.expected_previous_month || "..."}; latest available {dgca?.latest_available_file || "..."}.</p><a href="https://www.dgca.gov.in/" target="_blank" rel="noreferrer">Open DGCA source</a></div><div className="panel wide"><h2>Data & Method</h2><div className="metric-grid"><div><span className="metric-label">Daily source routes</span><strong>{runCount}</strong></div><div><span className="metric-label">DGCA basket</span><strong>{method?.basket?.count ?? "..."}</strong></div><div><span className="metric-label">Valid observations</span><strong>{method?.quality?.by_quality_status?.valid?.toLocaleString() ?? "..."}</strong></div><div><span className="metric-label">Sources</span><strong>{method?.sources?.length ?? "..."}</strong></div></div><ul className="compact-list"><li>DGCA pairs expand to both directions in bidirectional mode.</li><li>CompareFlights and Ixigo run independently in background jobs.</li><li>Clean artifacts are route-complete before the dashboard uses them.</li><li>Missing fare components remain unavailable rather than estimated.</li></ul></div>
  </section></main>;
}
