"use client";
import { useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const COLORS = ["#0f4c81", "#b42318", "#138a36", "#9a6700", "#7a3e9d", "#007c91", "#d35400", "#40566f"];
const money = value => Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 });

export default function MultiLineChart({ series = [], yLabel = "Average payable fare" }) {
  const [windowSize, setWindowSize] = useState(0);
  const valid = series.map((item, index) => ({ ...item, color: COLORS[index % COLORS.length], points: (item.series || []).filter(point => point.value != null).map(point => ({ ...point, value: Number(point.value) })) })).filter(item => item.points.length);
  const dates = useMemo(() => [...new Set(valid.flatMap(item => item.points.map(point => point.date)))].sort((a, b) => { const an = Number(String(a).replace(/[^0-9]/g, "")); const bn = Number(String(b).replace(/[^0-9]/g, "")); return Number.isNaN(an) || Number.isNaN(bn) ? String(a).localeCompare(String(b)) : an - bn; }), [valid]);
  if (!valid.length) return <p className="muted">No route fare history is available for this selection.</p>;
  const visibleDates = windowSize ? dates.slice(Math.max(0, dates.length - windowSize)) : dates;
  const data = visibleDates.map(date => ({ date, ...Object.fromEntries(valid.map(item => [item.route, item.points.find(point => point.date === date)?.value ?? null])) }));
  return <div className="chart-shell chart-recharts"><ResponsiveContainer width="100%" height={340}><LineChart data={data} margin={{ top: 14, right: 18, left: 4, bottom: 25 }}><CartesianGrid stroke="#dfe7ee" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" type="category" tick={{ fontSize: 11, fill: "#5d6978" }} minTickGap={24} tickMargin={8} /><YAxis tick={{ fontSize: 11, fill: "#5d6978" }} tickFormatter={money} width={68} label={{ value: yLabel, angle: -90, position: "insideLeft", fill: "#5d6978", fontSize: 11 }} /><Tooltip content={({ active, payload, label }) => active && payload?.length ? <div className="recharts-tooltip"><strong>{label}</strong>{payload.filter(item => item.value != null).map(item => <span key={item.dataKey} style={{ color: item.color }}>{item.name}: Rs {money(item.value)}</span>)}</div> : null} /><Legend wrapperStyle={{ fontSize: 12, paddingTop: 8 }} />{valid.map(item => <Line key={item.route} type="monotone" dataKey={item.route} name={item.label || item.route} stroke={item.color} strokeWidth={2.5} dot={{ r: 3, strokeWidth: 1, fill: item.color }} activeDot={{ r: 6, stroke: "#fff", strokeWidth: 2 }} connectNulls={false} isAnimationActive animationDuration={650} />)}</LineChart></ResponsiveContainer><div className="chart-actions"><button type="button" onClick={() => setWindowSize(size => size ? Math.min(dates.length, size + 10) : dates.length)}>Show more</button><button type="button" onClick={() => setWindowSize(size => Math.max(10, size ? size - 10 : Math.max(10, dates.length - 10)))} disabled={dates.length <= 10}>Zoom in</button><button type="button" onClick={() => setWindowSize(0)}>All dates</button></div><p className="chart-note">Hover a point to inspect the exact {yLabel.toLowerCase()} for each route or lead-time window.</p></div>;
}
