"use client";
import { useEffect, useMemo, useState } from "react";
import TrendChart from "../components/TrendChart";
import MultiLineChart from "../components/MultiLineChart";
import BarChart from "../components/BarChart";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "/api/backend";
const PAGE_SIZE = 10;

export default function RouteExplorer() {
  const [basket, setBasket] = useState(null); const [routes, setRoutes] = useState([]); const [selected, setSelected] = useState(""); const [detail, setDetail] = useState(null); const [forecast, setForecast] = useState(null); const [offerSort, setOfferSort] = useState("fare"); const [airports, setAirports] = useState({}); const [analytics, setAnalytics] = useState([]); const [routeFilter, setRouteFilter] = useState(""); const [analyticsSort, setAnalyticsSort] = useState("average_fare"); const [rankingPage, setRankingPage] = useState(1);
  useEffect(() => { let config = { topN: 50, direction: "bidirectional" }; try { config = { ...config, ...JSON.parse(localStorage.getItem("airfareSettings") || "{}") }; } catch {} fetch(`${API_URL}/api/dgca/basket?top_n=${config.topN}&direction_mode=${config.direction}`).then(r => r.json()).then(data => { setBasket(data); setRoutes(data.routes || []); if (data.routes?.[0]) setSelected(`${data.routes[0].origin}-${data.routes[0].destination}`); }); fetch(`${API_URL}/api/airports`).then(r => r.json()).then(data => setAirports(Object.fromEntries((data.airports || []).map(a => [a.code, a])))); fetch(`${API_URL}/api/routes/analytics`).then(r => r.json()).then(data => setAnalytics(data.routes || [])); }, []);
  useEffect(() => { if (!selected) return; const [origin, destination] = selected.split("-"); fetch(`${API_URL}/api/routes/${origin}/${destination}`).then(r => r.ok ? r.json() : null).then(setDetail); fetch(`${API_URL}/api/forecast/${origin}/${destination}`).then(r => r.ok ? r.json() : null).then(setForecast).catch(() => setForecast(null)); }, [selected]);
  const snapshot = detail?.market_snapshot; const fmtFare = value => value == null ? "Unavailable" : `Rs ${Number(value).toLocaleString("en-IN")}`; const fmtDuration = minutes => minutes == null ? "Unavailable" : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
  const sortedOffers = [...(detail?.offers || [])].sort((a, b) => offerSort === "airline" ? `${a.airline_name || ""}`.localeCompare(`${b.airline_name || ""}`) : offerSort === "duration" ? (a.duration_minutes ?? 99999) - (b.duration_minutes ?? 99999) : offerSort === "stops" ? (a.stops ?? 99) - (b.stops ?? 99) : (a.payable_fare ?? 99999999) - (b.payable_fare ?? 99999999));
  const routeTitle = detail?.route ? `${airports[detail.route.origin]?.name || detail.route.origin} (${detail.route.origin}) to ${airports[detail.route.destination]?.name || detail.route.destination} (${detail.route.destination})` : "Route market";
  const filteredAnalytics = useMemo(() => [...analytics].filter(row => `${row.origin} ${row.destination} ${row.airline_code}`.toLowerCase().includes(routeFilter.toLowerCase())).sort((a, b) => analyticsSort === "route" ? `${a.origin}-${a.destination}`.localeCompare(`${b.origin}-${b.destination}`) : analyticsSort === "airline" ? a.airline_code.localeCompare(b.airline_code) : (b[analyticsSort] ?? -Infinity) - (a[analyticsSort] ?? -Infinity)), [analytics, routeFilter, analyticsSort]);
  const selectedRanking = filteredAnalytics.filter(row => !selected || `${row.origin}-${row.destination}` === selected);
  const rankingRows = selectedRanking.length ? selectedRanking : filteredAnalytics; const pageCount = Math.max(1, Math.ceil(rankingRows.length / PAGE_SIZE)); const pageRows = rankingRows.slice((rankingPage - 1) * PAGE_SIZE, rankingPage * PAGE_SIZE);
  const exportRoutes = () => { const columns = ["route", "origin_airport", "destination_airport", "airline_code", "average_fare", "median_fare", "lowest_fare", "highest_fare", "observation_count", "latest_index"]; const csv = [columns.join(","), ...rankingRows.map(row => [`${row.origin}-${row.destination}`, `${airports[row.origin]?.name || ""} (${row.origin})`, `${airports[row.destination]?.name || ""} (${row.destination})`, row.airline_code, row.average_fare, row.median_fare, row.lowest_fare, row.highest_fare, row.observation_count, row.latest_index ?? ""].map(value => `"${String(value).replaceAll('"', '""')}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = `airfare-${selected || "routes"}-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  useEffect(() => setRankingPage(1), [selected, routeFilter, analyticsSort]);
  return <main className="page"><section className="grid">
    <div className="panel full"><h2>Route Explorer</h2><div className="button-row route-picker"><label htmlFor="route">Route</label><select id="route" value={selected} onChange={e => setSelected(e.target.value)}>{routes.map((r, i) => <option key={`${r.origin}-${r.destination}-${i}`} value={`${r.origin}-${r.destination}`}>{airports[r.origin]?.name || r.origin} ({r.origin}) to {airports[r.destination]?.name || r.destination} ({r.destination}) | rank {r.rank}</option>)}</select></div><p className="muted">Basket window {basket?.metadata?.window_start ?? "..."} to {basket?.metadata?.window_end ?? "..."}. Select a route to inspect its market, airlines, lead-time windows, and offers.</p></div>
    <div className="panel full"><h2>{routeTitle}</h2><div className="metric-grid"><div><span className="metric-label">Lowest payable fare</span><strong>{fmtFare(snapshot?.lowest_payable_fare)}</strong></div><div><span className="metric-label">Average payable fare</span><strong>{fmtFare(snapshot?.average_payable_fare)}</strong></div><div><span className="metric-label">Imported observations</span><strong>{snapshot?.observation_count ?? "Unavailable"}</strong></div><div><span className="metric-label">Route index</span><strong>{detail?.history?.at(-1)?.index_value?.toFixed(2) ?? "Unavailable"}</strong></div></div><p className="muted">Airfare index values are separate from payable fares. Regulatory fare components are unavailable when the source does not expose them separately.</p></div>
    <div className="panel wide"><h2>Airlines On Route</h2>{snapshot?.airlines?.length ? <table><thead><tr><th>Airline</th><th>Records</th><th>Lowest fare</th><th>Average fare</th></tr></thead><tbody>{snapshot.airlines.map(a => <tr key={a.airline_code}><td>{a.airline_name} ({a.airline_code})</td><td>{a.record_count}</td><td>{fmtFare(a.lowest_fare)}</td><td>{fmtFare(a.average_fare)}</td></tr>)}</tbody></table> : <p className="muted">No imported airline observations are available for this direction.</p>}</div>
    <div className="panel wide"><h2>Fare Components</h2><table><tbody><tr><th>Base fare</th><td>{fmtFare(snapshot?.fare_components?.base_fare)}</td></tr><tr><th>Taxes</th><td>{fmtFare(snapshot?.fare_components?.taxes)}</td></tr><tr><th>Airport charges</th><td>{fmtFare(snapshot?.fare_components?.airport_charges)}</td></tr><tr><th>Mandatory total</th><td>{snapshot?.fare_components?.mandatory_total ?? "Unavailable"}</td></tr></tbody></table></div>
    <div className="panel wide"><h2>Route Index</h2>{detail?.history?.length ? <TrendChart data={detail.history.map(h => ({ date: h.index_date, value: h.index_value }))} yLabel="Route index" color="#138a36" /> : <p className="muted">No route index history is available for this route.</p>}</div>
    <div className="panel wide"><h2>Forecast Signal</h2>{forecast ? <table><thead><tr><th>Days to departure</th><th>Predicted fare</th><th>Range</th></tr></thead><tbody>{forecast.forecast.map(f => <tr key={f.days_to_departure}><td>{f.days_to_departure}</td><td>Rs {f.predicted_fare.toLocaleString()}</td><td>Rs {f.lower_bound.toLocaleString()} to Rs {f.upper_bound.toLocaleString()}</td></tr>)}</tbody></table> : <p className="muted">Forecast appears when enough stored observations exist.</p>}</div>
    <div className="panel full"><h2>Route Fare By Airline And Lead Time</h2><MultiLineChart series={snapshot?.lead_time_series || []} yLabel="Average fare (Rs)" /><p className="muted">Compare airlines across T+1, T+7, T+15, T+30, and T+45. Hover for the exact fare at each lead-time window.</p></div>
    <div className="panel full"><h2>Available Flight Observations</h2>{detail?.offers?.length ? <><div className="button-row table-tools"><label htmlFor="offer-sort">Sort offers</label><select id="offer-sort" value={offerSort} onChange={e => setOfferSort(e.target.value)}><option value="fare">Lowest fare</option><option value="airline">Airline</option><option value="duration">Shortest duration</option><option value="stops">Fewest stops</option></select></div><table><thead><tr><th>Airline / flight</th><th>Travel date</th><th>Departure</th><th>Duration</th><th>Stops</th><th>Fare</th><th>Baggage</th></tr></thead><tbody>{sortedOffers.map((o, i) => <tr key={`${o.flight_number}-${o.travel_date}-${i}`}><td>{o.airline_name} ({o.airline_code || "n/a"})<br /><span className="muted">{o.flight_number || "Flight unavailable"}</span></td><td>{o.travel_date}<br /><span className="muted">{o.advance_purchase_days} days before</span></td><td>{o.departure ? new Date(o.departure).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Unavailable"}</td><td>{fmtDuration(o.duration_minutes)}</td><td>{o.stops == null ? "Unavailable" : o.stops === 0 ? "Non-stop" : `${o.stops} stop`}</td><td><strong>{fmtFare(o.payable_fare)}</strong><br /><span className="muted">{o.fare_code || "Fare code unavailable"}</span></td><td>{o.checkin_baggage_kg == null ? "n/a" : `${o.checkin_baggage_kg} kg check-in`}<br />{o.cabin_baggage_kg == null ? "" : `${o.cabin_baggage_kg} kg cabin`}</td></tr>)}</tbody></table></> : <p className="muted">No available imported observations are stored for this route.</p>}</div>
    <div className="panel full"><div className="section-heading"><div><h2>Average Fare Ranking And Export</h2><p className="muted">Route: {selected || "select a route"}. Every available airline is ranked for the selected route.</p></div><BarChart data={[]} /></div><div className="button-row table-tools"><label htmlFor="route-filter">Filter route or airline</label><input id="route-filter" value={routeFilter} onChange={e => setRouteFilter(e.target.value)} placeholder="DEL, BOM, 6E..." /><label htmlFor="route-sort">Sort</label><select id="route-sort" value={analyticsSort} onChange={e => setAnalyticsSort(e.target.value)}><option value="average_fare">Average fare</option><option value="median_fare">Median fare</option><option value="observation_count">Observations</option><option value="latest_index">Latest index</option><option value="route">Route</option><option value="airline">Airline</option></select><button type="button" onClick={exportRoutes}>Export all filtered CSV</button></div><BarChart data={rankingRows.map(row => ({ label: `${row.origin}-${row.destination} / ${row.airline_code}`, value: row.average_fare }))} valueLabel="Average fare (Rs)" /><table><thead><tr><th>Route and airports</th><th>Airline</th><th>Average</th><th>Median</th><th>Low / high</th><th>Observations</th><th>Index</th></tr></thead><tbody>{pageRows.map((row, i) => <tr key={`${row.origin}-${row.destination}-${row.airline_code}-${i}`}><td><strong>{row.origin}-{row.destination}</strong><br /><span className="muted">{airports[row.origin]?.name || "Unknown"} to {airports[row.destination]?.name || "Unknown"}</span></td><td>{row.airline_code}</td><td>{fmtFare(row.average_fare)}</td><td>{fmtFare(row.median_fare)}</td><td>{fmtFare(row.lowest_fare)} / {fmtFare(row.highest_fare)}</td><td>{row.observation_count.toLocaleString()}</td><td>{row.latest_index?.toFixed(2) ?? "n/a"}</td></tr>)}</tbody></table><div className="pagination"><span>Page {rankingPage} of {pageCount} | {rankingRows.length} rows</span><button type="button" onClick={() => setRankingPage(page => Math.max(1, page - 1))} disabled={rankingPage === 1}>Previous</button><button type="button" onClick={() => setRankingPage(page => Math.min(pageCount, page + 1))} disabled={rankingPage === pageCount}>Next page</button></div><p className="muted">The CSV export includes all filtered rows, including rows on later pages.</p></div>
    <div className="panel full"><h2>Top 50 Routes From DGCA</h2><table><thead><tr><th>Rank</th><th>Pair</th><th>Direction</th><th>Weight</th><th>Passengers</th></tr></thead><tbody>{routes.slice(0, 50).map((r, i) => <tr key={`${r.origin}-${r.destination}-${i}`}><td>{r.rank}</td><td>{r.pair_route}</td><td>{r.origin}-{r.destination}</td><td>{(r.directional_weight * 100).toFixed(3)}%</td><td>{r.total_pax_12_months.toLocaleString()}</td></tr>)}</tbody></table></div>
  </section></main>;
}
